version: '3.9'

services:
  db:
    image: postgres:15
    env_file:
      - ./app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - yadro_network
  backend:
    build: ./
    env_file:
      - ./app/.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      retries: 10
    ports:
      - "8080:8080"
    networks:
      - yadro_network

networks:
  yadro_network:
    driver: bridge

volumes:
  postgres_data:
